spring:
  main:
    allow-circular-references: true
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: 'create-drop'

  datasource:
    url: jdbc:postgresql://localhost:5436/booking_service_db
    username: postgres
    password: postgres
    hikari:
      schema: hbs_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS hbs_schema
      connection-timeout: 10000
