version: '3.8'

services:
  postgres:
    image: postgres:17
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=booking_service_db